Add files via upload
zerzd@HONOR_TANDEP MINGW64 ~ (master)
$ git config --global user.name "Anna Dorozhenko"

zerzd@HONOR_TANDEP MINGW64 ~ (master)
$ git config --global user.email DorozhenkoAS@mail.ru

zerzd@HONOR_TANDEP MINGW64 ~ (master)
$ cd D:/Анна_Дороженко/Home1

zerzd@HONOR_TANDEP MINGW64 /d/Анна_Дороженко/Home1
$ git init
Initialized empty Git repository in D:/Анна_Дороженко/Home1/.git/

zerzd@HONOR_TANDEP MINGW64 /d/Анна_Дороженко/Home1 (master)
$ git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .idea/

nothing added to commit but untracked files present (use "git add" to track)

zerzd@HONOR_TANDEP MINGW64 /d/Анна_Дороженко/Home1 (master)
$ git add *.txt
fatal: pathspec '*.txt' did not match any files

zerzd@HONOR_TANDEP MINGW64 /d/Анна_Дороженко/Home1 (master)
$ git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .idea/
        Home1.iml
        Test.java
        out/

nothing added to commit but untracked files present (use "git add" to track)

zerzd@HONOR_TANDEP MINGW64 /d/Анна_Дороженко/Home1 (master)
$ git add *.txt
fatal: pathspec '*.txt' did not match any files

zerzd@HONOR_TANDEP MINGW64 /d/Анна_Дороженко/Home1 (master)
$ git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .idea/
        Home1.iml
        Test.java
        out/

nothing added to commit but untracked files present (use "git add" to track)

zerzd@HONOR_TANDEP MINGW64 /d/Анна_Дороженко/Home1 (master)
$ git add *.java

zerzd@HONOR_TANDEP MINGW64 /d/Анна_Дороженко/Home1 (master)
$ git status
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
        new file:   Test.java

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .idea/
        Home1.iml
        out/


zerzd@HONOR_TANDEP MINGW64 /d/Анна_Дороженко/Home1 (master)
$ git commit -m "all java files were added to the project"
[master (root-commit) 305c7de] all java files were added to the project
 1 file changed, 6 insertions(+)
 create mode 100644 Test.java

zerzd@HONOR_TANDEP MINGW64 /d/Анна_Дороженко/Home1 (master)
$ git log
commit 305c7de263d78cd84f27d1abe12970445e878734 (HEAD -> master)
Author: Anna Dorozhenko <DorozhenkoAS@mail.ru>
Date:   Sun Dec 15 21:11:39 2024 +0700

    all java files were added to the project

zerzd@HONOR_TANDEP MINGW64 /d/Анна_Дороженко/Home1 (master)
$ git diff

zerzd@HONOR_TANDEP MINGW64 /d/Анна_Дороженко/Home1 (master)
$ git add test_resource.txt
fatal: pathspec 'test_resource.txt' did not match any files

zerzd@HONOR_TANDEP MINGW64 /d/Анна_Дороженко/Home1 (master)
$ git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .idea/
        Home1.iml
        Test2.java
        out/

nothing added to commit but untracked files present (use "git add" to track)

zerzd@HONOR_TANDEP MINGW64 /d/Анна_Дороженко/Home1 (master)
$ git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .idea/
        Home1.iml
        Test2.java
        example.txt
        out/

nothing added to commit but untracked files present (use "git add" to track)

zerzd@HONOR_TANDEP MINGW64 /d/Анна_Дороженко/Home1 (master)
$ git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .idea/
        Home1.iml
        Test2.java
        example.txt
        out/
        test2.txt

nothing added to commit but untracked files present (use "git add" to track)

zerzd@HONOR_TANDEP MINGW64 /d/Анна_Дороженко/Home1 (master)
$ git add *.txt

zerzd@HONOR_TANDEP MINGW64 /d/Анна_Дороженко/Home1 (master)
$ git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   example.txt
        new file:   test2.txt

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .idea/
        Home1.iml
        Test2.java
        out/


zerzd@HONOR_TANDEP MINGW64 /d/Анна_Дороженко/Home1 (master)
$ git commit -m “all txt files were added to the project”
error: pathspec 'txt' did not match any file(s) known to git
error: pathspec 'files' did not match any file(s) known to git
error: pathspec 'were' did not match any file(s) known to git
error: pathspec 'added' did not match any file(s) known to git
error: pathspec 'to' did not match any file(s) known to git
error: pathspec 'the' did not match any file(s) known to git
error: pathspec 'project”' did not match any file(s) known to git

zerzd@HONOR_TANDEP MINGW64 /d/Анна_Дороженко/Home1 (master)
$ git log
commit 305c7de263d78cd84f27d1abe12970445e878734 (HEAD -> master)
Author: Anna Dorozhenko <DorozhenkoAS@mail.ru>
Date:   Sun Dec 15 21:11:39 2024 +0700

    all java files were added to the project

zerzd@HONOR_TANDEP MINGW64 /d/Анна_Дороженко/Home1 (master)